dataset:
  path:
    BUV2022:
      - True
      - '/dataset/cv/video/US/all'
    CVC612:
      - False
      - '/workspace/ex_data/CVC-ClinicDB/'

trainer:
  finetune_save_dir: 'CHECK_POINT_SlimUnetr'
  train_ratio: 0.8
  formal_size: 240
  in_channels: 3
  batch_size: 70
  num_workers: 16
  mixed_precision: 'no'
  gradient_accumulation_steps: 1
  optimizer:
    opt: 'adamw'
    weight_decay: 0.05
    lr: 0.0001
    # lr: 0.0005
  scheduler:
    warmup_epochs: 2
  num_epochs: 200

model:
  bas:
    in_channels: 3
    out_channels: 1
    embed_dim: 120
    #    embed_dim: 144
    embeding_dim: 225
    channels: [ 48, 96 ]
    #    channels: [36, 72]
    heads: [ 1, 4, 8 ]
    # S
    blocks: [1, 3, 3]
    # L
    # blocks: [ 1, 2, 3 ]
    r: [ 4, 2, 2 ]
    distillation: False
    conv_r: [ 4, 2, 2 ]
    dropout: 0.3
